services:
  mysql:
    container_name: mysql_9
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taller_9
      MYSQL_USER: user9
      MYSQL_PASSWORD: pass9
    ports:
      - "3216:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - express_sql_network

volumes:
  mysql_data:

networks:
  express_sql_network:
    driver: bridge